### ISSUE TITLE
`runtests` output

### ISSUE THREAD

**Issue by fcard** [coderofsalvation/powscript#25]
I like the idea of `runtests` making it more clear what file is being tested, but the current output is a bit noisy and hard to read. What do you think of the output [here](https://travis-ci.org/fcard/powscript/builds/154247007), using colors and indentation to do the separation?

**Comment by coderofsalvation** [comment]
very good, would definately merge that

**Comment by coderofsalvation** [comment]
merged PR https://github.com/coderofsalvation/powscript/pull/26
