### ISSUE TITLE
Function argument list syntax should maybe match array syntax

### ISSUE THREAD

**Issue by fcard** [coderofsalvation/powscript#41]
I was wondering if it wouldn't be more consistent that instead of
```sh
f(a,b,c)
```
We used
```sh
f(a b c)
```
Which is the same syntax for lists/arrays. As far as I can tell languages tend to have the same syntax for argument lists and their `(x,y,z)` collection type.

We could also do like clojure and have `,` just act like whitespace inside lists, but I am not sure that's a good idea, specially in a shell language where `,` is a string like most things, instead of special syntax.

The idea came from me implementing argument lists in terms of list syntax in #38, so I already have this working:
![live_powscript_funcarg3-s](https://user-images.githubusercontent.com/12222927/32705516-06b1c474-c7f4-11e7-96f2-7b6a305933c3.gif)
I can easily add the requirement for commas in argument lists only but it got me thinking about this.

**Comment by coderofsalvation** [comment]
i definately like the space-separated approach.
Its less noisy, and very human readable..like bash was intended :)
