### ISSUE TITLE
multiple function arguments caught a cold

### ISSUE THREAD

**Issue by coderofsalvation** [coderofsalvation/powscript#51]
@fcard: any idea how to revive the multiple function arguments?
I noticed this one is not included in the `.tools/runtests` suite:

![screenshot 2018-08-28 at 16 45 09](https://user-images.githubusercontent.com/180068/44730781-fe8fca80-aae1-11e8-85b5-76ce6c2bb095.png)

**Comment by fcard** [comment]
Remember #41? :p 
It should be `f(a b)` now. I must've forgotten to fix that test. Also, that should've halted the tests, I need to investigate that..

**Comment by coderofsalvation** [comment]
Oh! I noticed you've already updated the function reference.md :)
I didn't know that (It was still on my todo list) :D 
Ignore all my previous ignorant questions haha, I could've looked that up in the reference, my bad lol :)

**Comment by fcard** [comment]
Aw, it's fine, hehe. There are still a few things that need updating there, and a lot of new features to document... Isn't it great?

I need to reintroduce `set -e` to fix the tests not halting (maybe, but I would need to do that anyway at some point),  but I remember having trouble with that before.. Maybe I will take a look at that this weekend.
