### ISSUE TITLE
Automatic `set -e` might not be a good idea

### ISSUE THREAD

**Issue by fcard** [coderofsalvation/powscript#60]
The idea of halting on errors is very good and still worth exploring, but `set -e` has two problems:

1. It doesn't exist in POSIX mode
2. It's far from perfect and can be surprising

For point 2, check this link: http://mywiki.wooledge.org/BashFAQ/105

We can still have the "halting on error" without `set -e`, and we can do it more accurately since we have a compiler instead of a interpreter. It will take some work, tho.

**Comment by coderofsalvation** [comment]
I'm not sure on this one.
I agree `set -e` is not perfect, but better than nothing.
Lets re-open this issue in case we notice most people using powscript to port bash to powscript.
(Then it would be a priority i guess)
