### ISSUE TITLE
Windows CMD Support

### ISSUE THREAD

**Issue by jamesward** [coderofsalvation/powscript#64]
Not sure if it is feasible but it'd be amazing to have Windows CMD support.

**Comment by fcard** [comment]
I know relatively little windows cmd, but that does sound cool. I am interested in giving it a try at some point, although I am not sure how many features from bash can be implemented in cmd. (well, at least without it being too impractical)

**Comment by jamesward** [comment]
Thanks!  Wish I had some cycles to work on this.

**Comment by coderofsalvation** [comment]
not sure what is meant with Windows CMD?
If it's exporting .bat-scripts I'm afraid its not going to work, and out of scope for this project.
At least, unless there's some kind of supereasy way of doing that.
Windows best bet for scripting is powerscript, or bash-script using WSL.
