### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by ShalokShalom** [coderofsalvation/powscript#65]
Hi there :)

Your release page says there will be a new, upcoming compiler, much more robust and better. 

Is there any plan to release this soon?

I also take an early pre-release which I can test and help to improve, thanks.

**Comment by fcard** [comment]
The new compiler is already merged on master! See #38.

I am unsure what the plan for the next stable release is, although new testers are very welcome since I imagine there are a lot of issues with the new compiler we haven't found yet. I appreciate your interest very much!

**Comment by ShalokShalom** [comment]
Thats great. Maybe a public announcement?
